[package]
name = "matto"
version = "0.1.0"
authors = ["daniele <d.dorazio96@gmail.com>"]

[dependencies]
image = "0.19"
num = "0.1"
rand = "0.5.0-pre.0"
structopt = "0.2"

[dev-dependencies]
maplit = "1.0"
